from typing import Any, Optional, Sequence, Union

class CompilationError(Exception):
    diagnostic: dict[str, Any]

class ExecutionError(CompilationError):
    diagnostic: dict[str, Any]

class Kernel:
    def get_function_names(self) -> list[str]: ...
    def lookup_symbol(self, name: str) -> Optional[int]: ...
    def set_fuel(self, fuel: Optional[int] = None) -> None: ...
    def set_memory_quota(self, quota_bytes: int) -> None: ...
    def run(self, func_name: str, *args: Any) -> Any: ...
    def __call__(self, *args: Any) -> Any: ...

def check(source: str) -> dict[str, Any]: ...
def compile(source: str) -> Kernel: ...
def optimize(source: str) -> dict[str, Any]: ...
def assemble(source: str) -> bytes: ...
def disassemble(data: bytes) -> str: ...
def compile_binary(data: bytes) -> Kernel: ...
def register_symbol(name: str, ptr: int) -> None: ...
def load_library(path: str) -> None: ...
def get_symbol_address(name: str) -> Optional[int]: ...
def set_fuel(fuel: Optional[int]) -> None: ...
def get_remaining_fuel() -> Optional[int]: ...
def set_memory_quota(quota_bytes: int) -> None: ...
def get_allocated_memory() -> int: ...
def version() -> str: ...
def cpu_features() -> dict[str, Any]: ...
def set_isa_cap(level: Optional[str]) -> None: ...
def get_isa_cap() -> Optional[str]: ...
