"""
achainsaw In-Process Python Example: Zero-Copy SIMD with NumPy & Agent Self-Repair

Demonstrates:
1. Microsecond compilation of Cranelift bare-metal code from an agent.
2. In-process zero-copy mutation of a NumPy array using 128-bit SIMD registers.
3. Catching structured machine diagnostics for instant agent self-repair.
"""

import os
import sys
import time
import numpy as np

# Ensure root directory is on python path for achainsaw.pyd import
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
import achainsaw


def example_zero_copy_simd():
    print("--- 1. Zero-Copy SIMD Vector Processing with NumPy ---")

    # AIR SIMD Kernel: In-place scalar multiplication across 128-bit vector lanes
    air_kernel = """fn simd_scale(p:ptr, factor:f32, n:i64)
  b0:
    vfactor = splat factor
    zero = cst 0:i64
    jmp b1(zero)
  b1(i:i64):
    cond = lt i, n
    br cond, b2, b3
  b2:
    sixteen = cst 16:i64
    off = mul i, sixteen
    elem_ptr = add p, off
    v = ld elem_ptr:v128
    vscaled = vfmul v, vfactor
    st elem_ptr, vscaled
    one = cst 1:i64
    next_i = add i, one
    jmp b1(next_i)
  b3:
    ret
"""
    t0 = time.perf_counter()
    kernel = achainsaw.compile(air_kernel)
    t1 = time.perf_counter()
    print(f"JIT Compilation completed in {(t1 - t0) * 1000.0:.3f} ms")

    # Allocate contiguous 32-bit float array (32 elements = 8 SIMD vectors of 4xf32)
    arr = np.arange(1.0, 33.0, dtype=np.float32)
    print("Initial array head (first 8 elements):", arr[:8])

    # Execute JIT machine code directly on NumPy memory (zero copies)
    t0 = time.perf_counter()
    kernel.run("simd_scale", arr, 2.0, 8)
    t1 = time.perf_counter()
    print("Scaled array head (multiplied by 2.0):", arr[:8])
    print(f"Kernel execution time: {(t1 - t0) * 1_000_000.0:.2f} microseconds\n")


def example_agent_self_repair():
    print("--- 2. Autonomous Agent Self-Repair via Structured JSON Diagnostics ---")

    # Defective AIR snippet generated by an agent
    flawed_code = """fn compute(a:i32, b:i32)->i32
  b0:
    c = add a, non_existent_reg
    ret c
"""
    try:
        achainsaw.compile(flawed_code)
    except achainsaw.CompilationError as e:
        diag = e.diagnostic
        print(f"Caught CompilationError: [{diag['error_code']}] {diag['message']}")
        print(f"Location: Line {diag['span']['line']}, Column {diag['span']['column']}")
        print(f"Available registers for repair: {diag['context']['available_registers']}")
        print(f"Defective target: '{diag['context']['target']}'")

        # Simulated Agent Auto-Repair Logic:
        # Replace the missing register with an available valid register
        repaired_code = flawed_code.replace(
            diag["context"]["target"],
            diag["context"]["available_registers"][0]
        )
        print("\nAgent applied single-shot patch. Re-compiling...")
        k = achainsaw.compile(repaired_code)
        res = k.run("compute", 21, 0)
        print(f"Self-repair successful! compute(21, 0) = {res}")


if __name__ == "__main__":
    example_zero_copy_simd()
    example_agent_self_repair()
